export type Game = {
  id: string;
  name: string;
  blurb: string;
  min: number;
  max: number;
  time: string;
  minutes: number;
  bgg: number;
  difficulty: number;
  type: string;
  expansion?: boolean;
};

export const GAMES_INTRO = {
  deposit: 200,
  body: "Deskové hry z vitríny si můžete půjčit — společně s doplňky, jako je podložka, lampička nebo misky na herní mince — proti vratné záloze 200 Kč. Vypůjčenou hru a její obsah si, prosím, zkontrolujte podle seznamu na vnitřní straně víka krabice.",
};

export const GAMES: Game[] = [
  {
    id: "bang",
    name: "Bang",
    blurb:
      "Karetní hra, kde každý tajně ztělesňuje roli (šerif, bandita, odpadlík…) a snaží se splnit svůj cíl střelbou, blafováním a kombinacemi karet. Role ostatních neznáte — z tahů odhadujete, kdo je spojenec.",
    min: 4,
    max: 7,
    time: "20–45 min",
    minutes: 45,
    bgg: 5.9,
    difficulty: 1,
    type: "rodinná, karetní",
  },
  {
    id: "scrabble",
    name: "Scrabble",
    blurb:
      "Slovní hra: z náhodně tažených písmen skládáte slova na společné desce — jako křížovku. Body za písmena i za speciální políčka. Slovní zásoba i strategie.",
    min: 2,
    max: 4,
    time: "30–90 min",
    minutes: 90,
    bgg: 6.3,
    difficulty: 2.1,
    type: "rodinná, strategická, party",
  },
  {
    id: "cajova-zahrada",
    name: "Čajová zahrada",
    blurb:
      "Eurohra: pěstitelé čaje ve starověké Číně rozšiřují plantáže, sklízejí a fermentují čaj, kupují akční karty a spravují zdroje. Deck-building, volba akcí, hodnota lístků se mění.",
    min: 2,
    max: 4,
    time: "90–120 min",
    minutes: 120,
    bgg: 7.6,
    difficulty: 3,
    type: "strategická, ekonomická, farmaření",
  },
  {
    id: "bily-hrad",
    name: "Bílý hrad",
    blurb:
      "Eurohra v hradě Himedži. Vůdci klanů posílají služebníky do zahrad, na hradby i do Místnosti tisíce koberců. Umisťování kostek, správa zdrojů, tři kola.",
    min: 1,
    max: 4,
    time: "70–90 min",
    minutes: 90,
    bgg: 7.7,
    difficulty: 2.8,
    type: "strategická eurohra, dice placement",
  },
  {
    id: "bily-hrad-matcha",
    name: "Bílý hrad: Matcha",
    blurb:
      "Rozšíření — čajové obřady, gejši a zdroj časen. Čajovna, vyhlídka na jezírko, zelené kostky a tah navíc v každém kole.",
    min: 1,
    max: 4,
    time: "60–90 min",
    minutes: 90,
    bgg: 8.4,
    difficulty: 2.7,
    type: "rozšíření eurohry",
    expansion: true,
  },
  {
    id: "carcassonne",
    name: "Carcassonne",
    blurb:
      "Společně budujete krajinu: cesty, města, kláštery, louky. Družiníci jako rytíři, zloději, mniši, farmáři. Přístupná, s taktikou.",
    min: 2,
    max: 5,
    time: "30–45 min",
    minutes: 45,
    bgg: 7.4,
    difficulty: 1.9,
    type: "rodinná, tile placement",
  },
  {
    id: "carcassonne-cirkus",
    name: "Carcassonne: Cirkus",
    blurb:
      "Šapitó, akrobaté a principál. Představení boduje družiníky v okolí. Více interakce, stejná jednoduchost.",
    min: 2,
    max: 6,
    time: "cca 40 min",
    minutes: 40,
    bgg: 6.8,
    difficulty: 1,
    type: "rodinná, modulární rozšíření",
    expansion: true,
  },
  {
    id: "cyclades",
    name: "Cyclades",
    blurb:
      "Mytologické Řecko. Dražba o bohy: Ares armády, Poseidón lodě, Zeus kněze, Athena filozofy. První dvě metropole vyhrávají.",
    min: 2,
    max: 5,
    time: "60–90 min",
    minutes: 90,
    bgg: 7.5,
    difficulty: 2.8,
    type: "strategická, aukční, area control",
  },
  {
    id: "kryci-jmena",
    name: "Krycí jména",
    blurb:
      "Týmová slovní hra. Velitel jednoslovnou nápovědou vede tým ke svým agentům. Vyhnout se zabijákovi. Jednoduchá, hluboká v asociacích.",
    min: 2,
    max: 8,
    time: "15–30 min",
    minutes: 30,
    bgg: 7.7,
    difficulty: 1.3,
    type: "party, slovní, týmová",
  },
  {
    id: "milostny-dopis",
    name: "Milostný dopis",
    blurb:
      "Mikrohra: doručit dopis princezně. Jedna karta v ruce, líznete druhou. Odhalení, vyřazení, ochrana. Blafování v krátkých partiích.",
    min: 2,
    max: 6,
    time: "15–20 min",
    minutes: 20,
    bgg: 7.2,
    difficulty: 1.2,
    type: "karetní, dedukční, mikrohra",
  },
  {
    id: "monumenty-veku",
    name: "Monumenty věků",
    blurb:
      "Stavíte město s ikonickými památkami — Koloseum, pyramida. Zdroje, ulice, 3D monumenty se schopnostmi. Modulární mapa.",
    min: 1,
    max: 5,
    time: "45–75 min",
    minutes: 75,
    bgg: 7.9,
    difficulty: 2.2,
    type: "budovatelská, tile placement",
  },
  {
    id: "munchkin",
    name: "Munchkin",
    blurb:
      "Parodie fantasy RPG. Výbava, rasy, povolání, příšery, desátá úroveň. Humor, škodění soupeřům, chaos.",
    min: 3,
    max: 6,
    time: "60–90 min",
    minutes: 90,
    bgg: 6.1,
    difficulty: 1.8,
    type: "karetní, humorná, take that",
  },
  {
    id: "radlands",
    name: "Radlands: Gangy pustiny",
    blurb:
      "Duel dvou hráčů. Tři tábory k obraně, voda jako měna akcí. Agrese, obrana, synergie karet. Postapokalypsa.",
    min: 2,
    max: 2,
    time: "20–40 min",
    minutes: 40,
    bgg: 7.9,
    difficulty: 2.2,
    type: "karetní duel, taktická",
  },
  {
    id: "sky-team",
    name: "Sky Team",
    blurb:
      "Kooperace pro dva: pilot a kopilot. Přistání na světových letištích. Kostky na palubní desku, omezená komunikace.",
    min: 2,
    max: 2,
    time: "20–30 min",
    minutes: 30,
    bgg: 7.8,
    difficulty: 2,
    type: "kooperativní, pro dva",
  },
  {
    id: "vybusna-kotatka",
    name: "Výbušná koťátka",
    blurb:
      "Lízáte karty a doufáte, že ne kotě. Zneškodnění, nahlédnutí, škodolibost. Rychlá party hra.",
    min: 2,
    max: 5,
    time: "10–20 min",
    minutes: 20,
    bgg: 6.1,
    difficulty: 1,
    type: "party, karetní, humor",
  },
  {
    id: "maximalni-warp",
    name: "Maximální warp",
    blurb:
      "Sci-fi karty: proletět sektory galaxie dřív než soupeři. Unikátní lodě, asteroidy, piráti, poruchy.",
    min: 2,
    max: 6,
    time: "20–30 min",
    minutes: 30,
    bgg: 7.6,
    difficulty: 1.5,
    type: "karetní, sci-fi, závodní",
  },
  {
    id: "paladinove",
    name: "Paladinové západního království",
    blurb:
      "Eurohra: paladin určuje kolo, worker placement, víra, vliv, mise, opevnění. Asymetrie, hloubka.",
    min: 1,
    max: 4,
    time: "90–120 min",
    minutes: 120,
    bgg: 8.1,
    difficulty: 3.7,
    type: "strategická eurohra, worker placement",
  },
  {
    id: "paladinove-sidla",
    name: "Paladinové: Sídla šlechticů",
    blurb:
      "Rada šlechticů, vyslanci, tituly, noví paladini. Diplomacie a politický vliv navíc.",
    min: 1,
    max: 4,
    time: "120 min",
    minutes: 120,
    bgg: 8.3,
    difficulty: 3.8,
    type: "rozšíření eurohry, diplomacie",
    expansion: true,
  },
  {
    id: "dzin",
    name: "Džin",
    blurb:
      "Lovci džinů v poušti. Schopnosti džinů, esence, energie, pohyb po mapě. Silná tematika.",
    min: 1,
    max: 4,
    time: "60–90 min",
    minutes: 90,
    bgg: 7.7,
    difficulty: 2.7,
    type: "strategická, dobrodružná",
  },
  {
    id: "galakticke-aliance",
    name: "Galaktické aliance",
    blurb:
      "Kompaktní 4X. Tři frakce určují styl: obchod, válka, věda, diplomacie. Kolonizace, flotily, modulární mapa.",
    min: 1,
    max: 4,
    time: "45–60 min",
    minutes: 60,
    bgg: 7.5,
    difficulty: 2.8,
    type: "4X sci-fi, civilizace",
  },
  {
    id: "dorfromantik-sakura",
    name: "Dorfromantik: Sakura",
    blurb:
      "Kooperace v japonské krajině. Hexové destičky, kampaň, tajný obsah. Meditativní skládání mapy.",
    min: 1,
    max: 6,
    time: "60–90 min",
    minutes: 90,
    bgg: 8.1,
    difficulty: 2,
    type: "kooperativní, tile placement, kampaň",
  },
  {
    id: "naisi",
    name: "Naiši",
    blurb:
      "Abstraktní duel. Krátké tahy, žádná náhoda, předvídání. Minimalistická strategie.",
    min: 2,
    max: 2,
    time: "10–20 min",
    minutes: 20,
    bgg: 7.6,
    difficulty: 1.5,
    type: "abstraktní duel",
  },
  {
    id: "seti",
    name: "SETI",
    blurb:
      "Pátrání po mimozemské inteligenci. Observatoře, signály, technologie. Je to šum, nebo kontakt?",
    min: 1,
    max: 4,
    time: "60–120 min",
    minutes: 120,
    bgg: 8.4,
    difficulty: 2.8,
    type: "strategická, vědecká, engine-building",
  },
  {
    id: "vladci",
    name: "Vládci",
    blurb:
      "Deck-building pro dva. Deset balíčků království, jiná strategie každou partii. Čistý motor karet.",
    min: 2,
    max: 2,
    time: "30–45 min",
    minutes: 45,
    bgg: 7.6,
    difficulty: 2.3,
    type: "deck-building, duel",
  },
  {
    id: "catan",
    name: "Osadníci z Catanu",
    blurb:
      "Ostrov, suroviny z kostek, cesty, vesnice, města, obchod, zloděj. Klasika diplomatické eurohry.",
    min: 3,
    max: 4,
    time: "60–90 min",
    minutes: 90,
    bgg: 7.1,
    difficulty: 2.3,
    type: "strategická, obchodní, rodinná",
  },
  {
    id: "port-royal",
    name: "Port Royal",
    blurb:
      "Karibský přístav. Risk při vykládání karet — dvě lodě stejné barvy a tah padá. Push-your-luck.",
    min: 2,
    max: 5,
    time: "20–50 min",
    minutes: 50,
    bgg: 7.2,
    difficulty: 1.8,
    type: "karetní, push-your-luck",
  },
  {
    id: "tash-kalar",
    name: "Tash-Kalar",
    blurb:
      "Souboj mágů. Vzory kamenů přivolávají bytosti. Prostor, načasování, školy magie.",
    min: 2,
    max: 4,
    time: "30–60 min",
    minutes: 60,
    bgg: 7.1,
    difficulty: 2.4,
    type: "abstraktní, taktická, aréna",
  },
  {
    id: "civilization",
    name: "Civilization",
    blurb:
      "Od prvního města k říši. Technologie, kultura, válka, diplomacie. Epická 4X, 2–4 hodiny.",
    min: 2,
    max: 4,
    time: "120–240 min",
    minutes: 240,
    bgg: 7.4,
    difficulty: 3.3,
    type: "4X civilizace",
  },
];
