export type MenuItem = { n: string; p: string; t?: string };
export type MenuCat = {
  id: string;
  title: string;
  hint?: string;
  tone: string;
  emoji: string;
  items: MenuItem[];
};

export const MENU_CATS: MenuCat[] = [
  {
    id: "caje",
    title: "Čaje",
    hint: "První cena = vlastní příprava. Druhá = hotový nálev (druhý nálev v ceně).",
    tone: "#8fbf8a",
    emoji: "🍃",
    items: [
      { n: "Pai Mu Tan — Bílá pivoňka", p: "115 / 135", t: "Fujian. Hedvábný, květinový. Čaj císařoven — na hladkou kůži i na večer." },
      { n: "Pi Lo Chun — Jarní spirálky", p: "119 / 139", t: "Jiangsu. Smaragdový nálev. Voní dřív, než ho poprvé zalejete." },
      { n: "Lung Ching — Dračí studna", p: "109 / 129", t: "Zhejiang. Čtyři poklady: barva, vůně, chuť, tvar. Císařův oblíbený." },
      { n: "White King — jasmínový", p: "109 / 129", t: "Zelený s květy jasmínu. Noc v čínské zahradě, nasládlá a svěží." },
      { n: "Zhu Cha — Gunpowder", p: "95 / 115", t: "Granule jako střelný prach. Z Číny připlul po moři a ostrost si nechal." },
      { n: "Genmaicha", p: "109 / 129", t: "Japonsko. Bancha s praženou rýží. Čaj rolníků, chutná jako dům." },
      { n: "Kukicha Sakuraba", p: "129 / 149", t: "Izu. Stonky a lístky sakury. Jaro, které se vejde do konvice." },
      { n: "Hojicha", p: "119 / 139", t: "Pražené stonky. Málo kofeinu, sušenka a čokoláda. Večer v Kjótu bez výčitek." },
      { n: "Kukicha BIO", p: "119 / 139", t: "Kagoshima. Sladká, plná. Jih Japonska, kde čaj zraje u moře." },
      { n: "Che Thai Nguyen superior", p: "99 / 119", t: "Hory Thai Nguyen. Trávovitě nasládlý. Vietnam pije čaj z misky." },
      { n: "Yuzu tea — Japonsko BIO", p: "109 / 129", t: "Kůra yuzu. Citrusově máslový. Zima, která voní koupelnou gejši." },
      { n: "Sencha", p: "dle nabídky", t: "Japonská klasika. Aktuální sorta u obsluhy — každý rok jiná." },
    ],
  },
  {
    id: "oolong",
    title: "Oolongy",
    tone: "#d4b483",
    emoji: "🍵",
    items: [
      { n: "Nai Xiang Jin Xua — Mléčný", p: "145 / 165", t: "Tchaj-wan. Karamelově mléčný. Ostrov, kde čaj umí chutnat jako dezert." },
      { n: "Phoenix Wu Dong Mi Lan Xiang", p: "135 / 155", t: "Chaozhou. Med, orchidej. Fénix z hor — pije se z malé konvičky." },
      { n: "Gui Hua Superior", p: "155 / 175", t: "Osmanthus. Citrus, dlouhý aftertaste. Květ, který Čína míchá do čaje od dynastie Song." },
      { n: "Tie Guan Yin King", p: "135 / 155", t: "Anxi. Železná bohyně milosrdenství. Květinová — dozvuk se nechce jít." },
      { n: "Da Hong Pao", p: "135 / 155", t: "Wuyi. Šarlatové roucho. Čaj, za který se kdysi platilo zlatem." },
      { n: "Ren Shen Oolong", p: "130 / 150", t: "Ženšen v oolongu. Jantar. Síla, která se tváří jako objetí." },
    ],
  },
  {
    id: "tmave",
    title: "Červené, černé, puerh",
    tone: "#c47a5a",
    emoji: "🍂",
    items: [
      { n: "Dian Hong Kung Fu — Medový polibek", p: "125 / 155", t: "Yunnan. Tmavě oranžový, med. Červené listy ze stromů starších než Praha." },
      { n: "Ceylon Tiger River", p: "95", t: "Kandy, Srí Lanka. Řízný, čokoládový. Čaj, který Britové vozili místo zlata." },
      { n: "Earl Grey", p: "99", t: "Bergamot. Lord Grey si ho nechal namíchat — my ho pijeme bez protokolu." },
      { n: "Darjeeling, Nepál", p: "dle nabídky", t: "Himálaj. U obsluhy. Čaj, který voní údolím, kde se rodí mlha." },
      { n: "Puerh tmavý sypaný", p: "99 / 119", t: "Yunnan. Zemitý, nasládlý. Zraje jako víno — čím starší, tím klidnější." },
      { n: "Puerh zelený — Maocha", p: "99 / 119", t: "Sušený na slunci. Jemný, květinový. Mladší bratr puerhu, ještě bez vousů." },
    ],
  },
  {
    id: "spec",
    title: "Speciality z konvice",
    tone: "#e2c56a",
    emoji: "✨",
    items: [
      { n: "Touareg", p: "99", t: "Maroko. Zelený čaj, máta, cukr. Čaj pouště — hostovi se nalévá třikrát." },
      { n: "Wayusa", p: "119", t: "Amazonie. Čistá energie, 15 min. List, kterým si Kichwa vyplachují sny." },
      { n: "Dátá Masala", p: "128", t: "Indie. Koření a mléko, až 30 min. Chai, který se vaří pomalu, jako řeč na trhu." },
      { n: "Zázvorový čaj", p: "115", t: "Čerstvý zázvor, citron, med. Léčivka, která se tváří jako flirt." },
      { n: "Karkade", p: "99", t: "Nil. Ibišek. Karmínový čaj faraonů — trpký, žízeň ho miluje." },
      { n: "Karkade se skořicí a vanilkou", p: "109", t: "Ibišek, skořice, vanilka. Orient, který se svlékl do dezertu." },
      { n: "Matcha latté teplé / studené 0,4 l", p: "99", t: "Japonská matcha v mléku. Ceremonie, která si sedla do sklenice." },
      { n: "Horká čokoláda 0,6 l", p: "129", t: "Pravá čokoláda a mléko. Střední Amerika, bez prášku z automatu." },
      { n: "Horká čokoláda se šlehačkou 0,25 l", p: "89", t: "Čokoláda se šlehačkou. Dětská vzpomínka, dospělá dávka." },
      { n: "Salep 0,25 l", p: "95", t: "Anatolie. Puding z orchideje, cca 15 min. Zima v Istanbulu, v hrnku." },
      { n: "Salep extra 0,25 l", p: "99", t: "S oříšky, kokosem, čokoládou nebo matchou. Istanbul, extra." },
      { n: "Yuzu tea Korea", p: "129", t: "Korea. Yuzu bez teinu. Vitamín C, který chutná jako slunce." },
    ],
  },
  {
    id: "nectaj",
    title: "Byliny, maté, ovocné",
    tone: "#7aaf8a",
    emoji: "🌿",
    items: [
      { n: "Babiččina zahrádka", p: "99", t: "Ibišek, bezinka, jablka. Česká zahrádka, ne import." },
      { n: "Bora bora", p: "99", t: "Tropické ovoce a vanilka. Polynésie, aniž byste vstali od stolu." },
      { n: "Maté IQ", p: "99", t: "Ginkgo, guarana, pomeranč. Hlava jasná — Jižní Amerika s asijským bonusem." },
      { n: "Večerní čaj", p: "99", t: "Heřmánek, meduňka. Byliny, které umí ztišit i Myslíkovu." },
      { n: "Rooibos červený", p: "99", t: "Cederberg, Jižní Afrika. Červený keř, žádný kofein, celý večer." },
      { n: "Maté Pampero", p: "99", t: "Pampa. Pražené, zemité. Kalabasa a bombilla, jako gauchos." },
      { n: "Maté Rancho", p: "99", t: "Zelené maté. Trávovitě svíravé. Ráno v pampě, večer v suterénu." },
      { n: "Maté Amigo", p: "109", t: "Pražené s karamelem. Maté, které se naučilo usmívat." },
    ],
  },
  {
    id: "cold",
    title: "Studené a limonády",
    tone: "#7ec8c4",
    emoji: "🧊",
    items: [
      { n: "Virgin mojito 0,6 l", p: "115", t: "Zelený čaj, limetka, máta. Havana bez rumu — pořád tančí." },
      { n: "Zázvorová limonáda 0,4 l", p: "89", t: "Čerstvý zázvor. Pálí slušně, chladí poctivě." },
      { n: "Citronáda 1 l", p: "139", t: "Citron. Klasika, kterou není třeba vylepšovat." },
      { n: "Kitl 0,4 / 1,0 l", p: "79 / 129", t: "České sirupy. Bezinka, višeň, malina — léto z láhve." },
      { n: "Džus pomeranč / jablko 0,4 l", p: "79", t: "Pomeranč nebo jablko. Přímo, bez příběhu navíc." },
      { n: "Džus s matchou 0,4 l", p: "89", t: "Džus s matchou. Japonsko potkalo lis." },
    ],
  },
  {
    id: "lahve",
    title: "Z vitríny",
    hint: "Berete rovnou z chladničky. Bez čekání.",
    tone: "#9bb7d4",
    emoji: "🍾",
    items: [
      { n: "Mattoni 0,33 l", p: "69", t: "Karlovy Vary. Minerálka z lázní, ne z kohoutku." },
      { n: "Club-Maté / Cola / Granát", p: "79–85", t: "Německé maté v plechu. Berlínská noc, české odpoledne." },
      { n: "Wostok BIO 0,33 l", p: "79", t: "Hruška, pomeranč, švestka. Východ, ale slušný." },
      { n: "Seicha matcha limonády 0,33 l", p: "79", t: "Japonský prach v bublinách. Black, grep, limeta, yuzu." },
      { n: "Bacilli kombucha / malinovka 0,33 l", p: "79", t: "Ferment, který se tváří osvěživě." },
      { n: "Tátův sad tonic / zázvorka 0,33 l", p: "79", t: "Tonic a zázvorka z českého sadu. Táta ví." },
    ],
  },
  {
    id: "alko",
    title: "Čajové drinky · 18+",
    hint: "Velký panák v drinku. Mojito 0,06 l.",
    tone: "#d4a0b0",
    emoji: "🍸",
    items: [
      { n: "Čajové mojito 0,6 l", p: "159", t: "Zelený čaj, rum, marocká máta. Havana potkala Marrakéš." },
      { n: "Višňový král 0,4 l", p: "149", t: "White King, vodka, višeň. Královský, ale neformální." },
      { n: "Jahodová bohyně 0,4 l", p: "149", t: "Tie Guan Yin, gin, jahoda. Bohyně, která pije s vámi." },
      { n: "Jasmínový Nik 0,4 l", p: "149", t: "Jasmín, gin, grep. Noční květ, denní ostrost." },
      { n: "Marocký citron 0,4 l", p: "149", t: "Touareg, gin, citrus. Poušť s ledem." },
      { n: "Geishino pohlazení 0,4 l", p: "149", t: "Roku gin, Kukicha, zázvor. Kjóto, které se umí přitulit." },
      { n: "Tuten drink 0,4 l", p: "149", t: "Karkade, černý rybíz, vodka. Egyptský ibišek v české noci." },
    ],
  },
  {
    id: "cider",
    title: "Cider a medovina",
    tone: "#e0b35c",
    emoji: "🍯",
    items: [
      { n: "Tátův cider 0,33 l", p: "89", t: "Český mošt. Suchý až višňový. Jablko, které se naučilo pít." },
      { n: "Bohemia cider 0,33 l", p: "89", t: "Cannabis, aronie, chilli. Čechy, ale ne poslušné." },
      { n: "Akátová medovina", p: "69 / 118", t: "Akát. 1 / 2 dcl. I v rohu, jak Kelti — med, který hřeje." },
      { n: "Staročeská medovina", p: "79 / 138", t: "Byliny, dubový sud. Medovina, jakou pili, než přišlo pivo." },
      { n: "Hidromiel Odin / Hela / Loki 0,33 l", p: "129", t: "Španělsko. Perlivá. Vikingové by se divili, že to umí i bublinky." },
    ],
  },
  {
    id: "jidlo",
    title: "Pochutiny a jídlo",
    tone: "#c4a07a",
    emoji: "🍽️",
    items: [
      { n: "Mandle, ořechy, chalva, ovoce", p: "39–65", t: "70 g. Sladké i slané." },
      { n: "Marlenka / se šlehačkou", p: "69 / 75" },
      { n: "Mochi Motiko", p: "69", t: "Matcha, mango, jahoda, pistácie…" },
      { n: "Kuskus zeleninový 450 g", p: "165" },
      { n: "Kuskus sýrový 500 g", p: "179" },
      { n: "Pita balkán / hermelín", p: "119" },
      { n: "Toasty sýrové, 2 ks", p: "109" },
      { n: "Indická jídla", p: "149", t: "Aloo, palak, matar, korma, biryani. Pita v ceně." },
    ],
  },
  {
    id: "dymky",
    title: "Vodní dýmky · 18+",
    hint: "Jen k nápoji. Uhlíky z kokosu, další v ceně. Po–Čt 13–15: Happy Hours 1+1.",
    tone: "#d4b483",
    emoji: "💨",
    items: [
      { n: "Adalya", p: "229", t: "Turecký základ nabídky." },
      { n: "Cult / Serbetli / Theo", p: "289" },
      { n: "Černé tabáky v mixu / na čisto", p: "320 / 370", t: "Tangiers, Darkside, Theo, Starbuzz Vintage." },
      { n: "Mléko do šíšy / mrazící šlauch", p: "+35" },
      { n: "Wookah luxus", p: "+85", t: "Led, citron, LED." },
      { n: "Luxus + mrazící šlauch", p: "+95" },
    ],
  },
];
