/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GatchaRouteImport } from './routes/gatcha'
import { Route as HryRouteImport } from './routes/hry'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as NakupRouteImport } from './routes/nakup'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as RezervaceRouteImport } from './routes/rezervace'
import { Route as SdileniRouteImport } from './routes/sdileni'
import { Route as SmenaRouteImport } from './routes/smena'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GatchaRoute = GatchaRouteImport.update({
  id: '/gatcha',
  path: '/gatcha',
  getParentRoute: () => rootRouteImport,
} as any)
const HryRoute = HryRouteImport.update({
  id: '/hry',
  path: '/hry',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const NakupRoute = NakupRouteImport.update({
  id: '/nakup',
  path: '/nakup',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const RezervaceRoute = RezervaceRouteImport.update({
  id: '/rezervace',
  path: '/rezervace',
  getParentRoute: () => rootRouteImport,
} as any)
const SdileniRoute = SdileniRouteImport.update({
  id: '/sdileni',
  path: '/sdileni',
  getParentRoute: () => rootRouteImport,
} as any)
const SmenaRoute = SmenaRouteImport.update({
  id: '/smena',
  path: '/smena',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gatcha': typeof GatchaRoute
  '/hry': typeof HryRoute
  '/menu': typeof MenuRoute
  '/nakup': typeof NakupRoute
  '/promo': typeof PromoRoute
  '/rezervace': typeof RezervaceRoute
  '/sdileni': typeof SdileniRoute
  '/smena': typeof SmenaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gatcha': typeof GatchaRoute
  '/hry': typeof HryRoute
  '/menu': typeof MenuRoute
  '/nakup': typeof NakupRoute
  '/promo': typeof PromoRoute
  '/rezervace': typeof RezervaceRoute
  '/sdileni': typeof SdileniRoute
  '/smena': typeof SmenaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gatcha': typeof GatchaRoute
  '/hry': typeof HryRoute
  '/menu': typeof MenuRoute
  '/nakup': typeof NakupRoute
  '/promo': typeof PromoRoute
  '/rezervace': typeof RezervaceRoute
  '/sdileni': typeof SdileniRoute
  '/smena': typeof SmenaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gatcha'
    | '/hry'
    | '/menu'
    | '/nakup'
    | '/promo'
    | '/rezervace'
    | '/sdileni'
    | '/smena'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gatcha'
    | '/hry'
    | '/menu'
    | '/nakup'
    | '/promo'
    | '/rezervace'
    | '/sdileni'
    | '/smena'
  id:
    | '__root__'
    | '/'
    | '/gatcha'
    | '/hry'
    | '/menu'
    | '/nakup'
    | '/promo'
    | '/rezervace'
    | '/sdileni'
    | '/smena'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GatchaRoute: typeof GatchaRoute
  HryRoute: typeof HryRoute
  MenuRoute: typeof MenuRoute
  NakupRoute: typeof NakupRoute
  PromoRoute: typeof PromoRoute
  RezervaceRoute: typeof RezervaceRoute
  SdileniRoute: typeof SdileniRoute
  SmenaRoute: typeof SmenaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatcha': {
      id: '/gatcha'
      path: '/gatcha'
      fullPath: '/gatcha'
      preLoaderRoute: typeof GatchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hry': {
      id: '/hry'
      path: '/hry'
      fullPath: '/hry'
      preLoaderRoute: typeof HryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nakup': {
      id: '/nakup'
      path: '/nakup'
      fullPath: '/nakup'
      preLoaderRoute: typeof NakupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rezervace': {
      id: '/rezervace'
      path: '/rezervace'
      fullPath: '/rezervace'
      preLoaderRoute: typeof RezervaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdileni': {
      id: '/sdileni'
      path: '/sdileni'
      fullPath: '/sdileni'
      preLoaderRoute: typeof SdileniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smena': {
      id: '/smena'
      path: '/smena'
      fullPath: '/smena'
      preLoaderRoute: typeof SmenaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GatchaRoute: GatchaRoute,
  HryRoute: HryRoute,
  MenuRoute: MenuRoute,
  NakupRoute: NakupRoute,
  PromoRoute: PromoRoute,
  RezervaceRoute: RezervaceRoute,
  SdileniRoute: SdileniRoute,
  SmenaRoute: SmenaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
